# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_no', models.CharField(blank=True, max_length=10, null=True)),
                ('activity_name', models.CharField(blank=True, max_length=20, null=True)),
                ('host_no', models.CharField(blank=True, max_length=10, null=True)),
                ('activity_description', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_time', models.DateTimeField(blank=True, null=True)),
                ('activity_max_participate', models.IntegerField(blank=True, null=True)),
                ('last_apply_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_no', models.CharField(blank=True, max_length=10, null=True)),
                ('host_name', models.CharField(blank=True, max_length=20, null=True)),
                ('host_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'activity_host',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActvityApplyment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actvity_no', models.CharField(blank=True, max_length=10, null=True)),
                ('sno', models.IntegerField(blank=True, null=True)),
                ('check_cancel_apply', models.IntegerField(blank=True, null=True)),
                ('check_apply_success', models.IntegerField(blank=True, null=True)),
                ('apply_time', models.DateTimeField(blank=True, null=True)),
                ('ad_no', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'actvity_applyment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_no', models.CharField(blank=True, max_length=10, null=True)),
                ('contributor', models.CharField(blank=True, max_length=20, null=True)),
                ('book_description', models.CharField(blank=True, max_length=255, null=True)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=20, null=True)),
                ('check_borrow', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookBorrowRecord',
            fields=[
                ('book_no', models.CharField(blank=True, max_length=10, null=True)),
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('check_cancel_apply', models.IntegerField(blank=True, null=True)),
                ('apply_time', models.DateTimeField(blank=True, null=True)),
                ('check_apply_success', models.IntegerField(blank=True, null=True)),
                ('ad_no', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'book_borrow_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_no', models.CharField(blank=True, max_length=10, null=True)),
                ('device_name', models.CharField(blank=True, max_length=20, null=True)),
                ('device_descript', models.CharField(blank=True, max_length=255, null=True)),
                ('device_amount', models.IntegerField(blank=True, null=True)),
                ('device_applied_amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'device',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceApplyment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(blank=True, null=True)),
                ('device_no', models.CharField(blank=True, max_length=10, null=True)),
                ('apply_time', models.DateTimeField(blank=True, null=True)),
                ('dor_no', models.CharField(blank=True, max_length=10, null=True)),
                ('check_cancel_apply', models.IntegerField(blank=True, null=True)),
                ('check_apply_success', models.IntegerField(blank=True, null=True)),
                ('return_device_time', models.DateTimeField(blank=True, null=True)),
                ('ad_no', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'device_applyment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DorAdminHandleLog',
            fields=[
                ('apply_time', models.DateTimeField(blank=True, null=True)),
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('dor_no', models.CharField(blank=True, max_length=10, null=True)),
                ('room_no', models.CharField(blank=True, max_length=10, null=True)),
                ('bed_no', models.CharField(blank=True, max_length=10, null=True)),
                ('apply_content', models.CharField(blank=True, max_length=250, null=True)),
                ('apply_status', models.CharField(blank=True, max_length=250, null=True)),
                ('ad_no', models.CharField(blank=True, max_length=10, null=True)),
                ('detail', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'dor_admin_handle_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DorChange',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(blank=True, max_length=20, null=True)),
                ('old_dor_no', models.CharField(blank=True, max_length=10, null=True)),
                ('old_room_no', models.CharField(max_length=10)),
                ('new_dor_no', models.CharField(blank=True, max_length=10, null=True)),
                ('new_room_no', models.CharField(blank=True, max_length=10, null=True)),
                ('apply_time', models.DateTimeField(blank=True, null=True)),
                ('stu_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dor_change',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DorCheckOut',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(blank=True, max_length=20, null=True)),
                ('room_no', models.CharField(max_length=10)),
                ('dor_no', models.CharField(blank=True, max_length=10, null=True)),
                ('apply_time', models.DateTimeField(blank=True, null=True)),
                ('stu_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dor_check_out',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DorCostRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(blank=True, null=True)),
                ('cost_no', models.CharField(blank=True, max_length=10, null=True)),
                ('item', models.CharField(blank=True, max_length=250, null=True)),
                ('fee', models.FloatField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dor_cost_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('dor_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dor_name', models.CharField(blank=True, max_length=20, null=True)),
                ('dor_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dormitory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DormitoryAdmin',
            fields=[
                ('dorm_admin_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dorm_admin_name', models.CharField(blank=True, max_length=20, null=True)),
                ('dor_no', models.CharField(blank=True, max_length=10, null=True)),
                ('dorm_admin_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('dorm_admin_email', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'dormitory_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DormitorySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dor_no', models.CharField(blank=True, max_length=20, null=True)),
                ('sno', models.IntegerField(blank=True, null=True)),
                ('room_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bed_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dormitory_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_room_no', models.CharField(blank=True, max_length=10, null=True)),
                ('meeting_room_size', models.CharField(blank=True, max_length=10, null=True)),
                ('include_medium_device', models.IntegerField(blank=True, db_column='Include_medium_device', null=True)),
                ('meeting_room_description', models.CharField(blank=True, max_length=255, null=True)),
                ('check_occupied', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meeting_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingRoomApplymentRecord',
            fields=[
                ('book_no', models.CharField(blank=True, max_length=10, null=True)),
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('check_cancel_apply', models.IntegerField(blank=True, null=True)),
                ('apply_time', models.DateTimeField(blank=True, null=True)),
                ('check_apply_success', models.IntegerField(blank=True, null=True)),
                ('ad_no', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'meeting_room_applyment_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingRoomOrderTime',
            fields=[
                ('meeting_room_order_time_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meeting_room_order_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RepairDeviceApplyment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(blank=True, null=True)),
                ('dor_no', models.CharField(blank=True, max_length=10, null=True)),
                ('room_no', models.CharField(blank=True, max_length=10, null=True)),
                ('stu_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('apply_repair_time', models.DateTimeField(blank=True, null=True)),
                ('ad_no', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'repair_device_applyment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(blank=True, max_length=10, null=True)),
                ('dor_no', models.CharField(blank=True, max_length=10, null=True)),
                ('bed_counts', models.IntegerField(blank=True, null=True)),
                ('room_descriptions', models.CharField(blank=True, max_length=255, null=True)),
                ('empty_beds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StayingApplyTime',
            fields=[
                ('staying_apply_time_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'staying_apply_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StayingOnVacationApplyment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(blank=True, null=True)),
                ('dor_no', models.CharField(blank=True, max_length=10, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('check_cancel_apply', models.IntegerField(blank=True, null=True)),
                ('check_apply_success', models.IntegerField(blank=True, null=True)),
                ('ad_no', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'staying_on_vacation_applyment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(blank=True, max_length=20, null=True)),
                ('college', models.CharField(blank=True, max_length=20, null=True)),
                ('major', models.CharField(blank=True, max_length=20, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dor_no', models.CharField(blank=True, max_length=10, null=True)),
                ('room_no', models.CharField(blank=True, max_length=10, null=True)),
                ('stu_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentStayingRecord',
            fields=[
                ('dor_no', models.CharField(blank=True, max_length=10, null=True)),
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(blank=True, max_length=20, null=True)),
                ('room_no', models.CharField(blank=True, max_length=10, null=True)),
                ('stu_phone', models.IntegerField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'student_staying_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StuPayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(blank=True, null=True)),
                ('bill_no', models.IntegerField(blank=True, null=True)),
                ('check_paied', models.IntegerField(blank=True, null=True)),
                ('pay_time', models.DateTimeField(blank=True, null=True)),
                ('dor_no', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'stu_pay_record',
                'managed': False,
            },
        ),
    ]
