# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminShowDorChangeApplymentLog',
            fields=[
                ('sno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('college_no', models.CharField(max_length=20)),
                ('major_no', models.CharField(max_length=20)),
                ('old_dor_no', models.CharField(max_length=10)),
                ('old_room_no', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=40)),
                ('new_dor_no', models.CharField(max_length=10)),
                ('new_room_no', models.CharField(max_length=10)),
                ('apply_time', models.DateTimeField()),
                ('phone', models.CharField(max_length=11)),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'admin_show_dor_change_applyment_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DorActivity',
            fields=[
                ('activity_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=20)),
                ('organization_no', models.CharField(max_length=10)),
                ('activity_description', models.CharField(max_length=100)),
                ('activity_time', models.DateTimeField()),
                ('activity_num_of_participate', models.IntegerField()),
                ('last_apply_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'dor_activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DorAdminAccount',
            fields=[
                ('ad_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'dor_admin_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DorBook',
            fields=[
                ('book_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('from_student', models.CharField(max_length=10)),
                ('book_description', models.CharField(max_length=10)),
                ('book_class', models.CharField(max_length=20)),
                ('is_borrowed', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'dor_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DorDevice',
            fields=[
                ('device_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=10)),
                ('device_description', models.CharField(max_length=100)),
                ('device_amount', models.IntegerField()),
                ('device_applied_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'dor_device',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DorRoom',
            fields=[
                ('room_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dor_no', models.CharField(max_length=10)),
                ('bed_counts', models.IntegerField()),
                ('room_description', models.CharField(max_length=100)),
                ('empty_beds', models.IntegerField()),
            ],
            options={
                'db_table': 'dor_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DorStuAccount',
            fields=[
                ('sno', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'dor_stu_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DorStudent',
            fields=[
                ('sno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('college_no', models.CharField(max_length=20)),
                ('major_no', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=1)),
                ('dor_no', models.CharField(max_length=10)),
                ('room_no', models.CharField(max_length=10)),
                ('mobilephone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'dor_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StuDorLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=20)),
                ('old_dor_no', models.CharField(max_length=10)),
                ('old_room_no', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=40)),
                ('new_dor_no', models.CharField(max_length=10)),
                ('new_room_no', models.CharField(max_length=10)),
                ('stu_phone', models.CharField(max_length=11)),
                ('reason', models.CharField(max_length=100)),
                ('apply_status', models.CharField(blank=True, max_length=10, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('apply_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stu_dor_log_model',
                'managed': False,
            },
        ),
    ]
